"""Quant-focused Monte Carlo pricing, basket, and exercise-analysis toolkit."""

from .american import AmericanOptionResult, price_american_option_lsm
from .basket import (
    BASKET_ARITHMETIC,
    BASKET_GEOMETRIC,
    BasketOptionSpec,
    build_equicorrelation_matrix,
    geometric_basket_price,
    price_basket_option_mc,
)
from .calibration import (
    CalibrationPoint,
    HestonCalibrationResult,
    HestonParameters,
    MarketOptionQuote,
    bundled_market_data_path,
    calibrate_heston_parameters,
    format_calibration_summary,
    format_calibration_table,
    load_market_quotes_csv,
    write_calibration_csv,
)
from .heston import (
    HestonResult,
    HestonSmilePoint,
    HestonSpec,
    format_heston_smile_table,
    implied_volatility_from_price,
    price_heston_option_cf,
    price_heston_option_mc,
    run_heston_smile,
    run_heston_smile_cf,
    write_heston_smile_csv,
)
from .pricing import (
    ASIAN_ARITHMETIC,
    CALL,
    EUROPEAN,
    PUT,
    UP_AND_OUT,
    GreeksEstimate,
    MonteCarloResult,
    OptionSpec,
    SimulationConfig,
    StudyResult,
    black_scholes_delta,
    black_scholes_gamma,
    black_scholes_price,
    black_scholes_vega,
    build_method_config,
    price_european_option_mc,
    price_option_mc,
)
from .report import build_research_report
from .sampling import halton_uniforms, inverse_normal_cdf
from .study import DEFAULT_METHODS, format_study_table, run_convergence_study, write_study_csv
from .surface import SurfacePoint, format_surface_table, run_sensitivity_surface, write_surface_csv

__all__ = [
    "ASIAN_ARITHMETIC",
    "AmericanOptionResult",
    "BASKET_ARITHMETIC",
    "BASKET_GEOMETRIC",
    "BasketOptionSpec",
    "CALL",
    "CalibrationPoint",
    "DEFAULT_METHODS",
    "EUROPEAN",
    "GreeksEstimate",
    "HestonCalibrationResult",
    "HestonParameters",
    "HestonResult",
    "HestonSmilePoint",
    "HestonSpec",
    "MarketOptionQuote",
    "MonteCarloResult",
    "OptionSpec",
    "PUT",
    "SimulationConfig",
    "StudyResult",
    "SurfacePoint",
    "UP_AND_OUT",
    "black_scholes_delta",
    "black_scholes_gamma",
    "black_scholes_price",
    "black_scholes_vega",
    "build_equicorrelation_matrix",
    "build_method_config",
    "build_research_report",
    "bundled_market_data_path",
    "calibrate_heston_parameters",
    "format_calibration_summary",
    "format_calibration_table",
    "format_study_table",
    "format_heston_smile_table",
    "format_surface_table",
    "geometric_basket_price",
    "halton_uniforms",
    "implied_volatility_from_price",
    "inverse_normal_cdf",
    "load_market_quotes_csv",
    "price_american_option_lsm",
    "price_basket_option_mc",
    "price_european_option_mc",
    "price_heston_option_cf",
    "price_heston_option_mc",
    "price_option_mc",
    "run_convergence_study",
    "run_heston_smile",
    "run_heston_smile_cf",
    "run_sensitivity_surface",
    "write_calibration_csv",
    "write_heston_smile_csv",
    "write_study_csv",
    "write_surface_csv",
]
